services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ogem-app-dev
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - ./:/app
      - /app/tmp
    depends_on:
      - valkey
    env_file:
      - .env
    environment: # This is needed for the dev container to work.
      - CONFIG_SOURCE=${CONFIG_SOURCE:-config.yaml}
      - CONFIG_TOKEN=${CONFIG_TOKEN:-}
      - OPEN_GEMINI_API_KEY=${OPEN_GEMINI_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY:-}
      - GENAI_STUDIO_API_KEY=${GENAI_STUDIO_API_KEY:-}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-}
      - VALKEY_ENDPOINT=${VALKEY_ENDPOINT:-valkey:6379}
      - RETRY_INTERVAL=${RETRY_INTERVAL:-5s}
      - PING_INTERVAL=${PING_INTERVAL:-30s}
    networks:
      - ogem-network
    command: ["air", "-c", ".air.toml"]

  valkey:
    image: valkey/valkey:latest
    container_name: ogem-valkey-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    command: valkey-server --appendonly yes
    environment:
      - VALKEY_MAX_MEMORY=256mb
      - VALKEY_MAX_MEMORY_POLICY=allkeys-lru
    networks:
      - ogem-network

networks:
  ogem-network:
    driver: bridge

volumes:
  valkey_data:
